import QuizEngine from "@/components/quiz/QuizEngine";

const QUESTIONS = [
  {
    question: "How does Machine Learning differ from traditional programming?",
    options: [
      "It requires more code to be written manually.",
      "Instead of providing rules to get answers, you provide data and answers to get the rules.",
      "It only runs on quantum computers.",
      "It relies entirely on if/else statements.",
    ],
    correctAnswer: 1,
  },
  {
    question: "What is the role of the 'Data' in the AI learning paradigm?",
    options: [
      "It is generated by the AI as output.",
      "It serves as the environment or examples the machine uses to figure out the underlying patterns.",
      "It is the compiled source code.",
      "It dictates the UI colors.",
    ],
    correctAnswer: 1,
  },
  {
    question:
      "True or False: Artificial Intelligence calculates the rules (logic) entirely on its own based on training examples.",
    options: ["True", "False"],
    correctAnswer: 0,
  },
];

export default function WhatIsAIQuiz() {
  return (
    <QuizEngine
      title="Level 0 • Paradigm Exam"
      moduleId="what-is-ai"
      track="ai"
      xpReward={100}
      passingScore={2}
      questions={QUESTIONS}
      returnPath="/ai"
      nextModulePath="/ai/vectors-and-matrices"
    />
  );
}
