"use client";

import Link from "next/link";
import CNNVisualizer from "@/components/canvas/CNNVisualizer";

export default function ComputerVisionPage() {
  return (
    <section className="flex h-full w-full overflow-hidden text-slate-200">
      <div className="w-1/3 min-w-[350px] max-w-[500px] bg-slate-900 border-r border-slate-800 flex flex-col z-10 shadow-2xl animate-slide-up">
        <div className="p-8 pb-0 mb-6">
          <p className="text-purple-500 font-bold tracking-widest uppercase text-sm mb-1">
            AI Track • Level 7
          </p>
          <h2 className="text-3xl font-bold text-white drop-shadow-md">
            Computer Vision (CNNs)
          </h2>
        </div>

        <div className="flex-1 overflow-y-auto custom-scrollbar p-8 pt-0">
          <div className="space-y-6 animate-fade-in text-sm leading-relaxed text-slate-300">
            <div>
              <p>
                Standard neural networks flatten images into long lists of
                numbers, destroying the spatial relationships between pixels. To
                solve this, we use{" "}
                <strong className="text-purple-400">
                  Convolutional Neural Networks (CNNs)
                </strong>
                .
              </p>
            </div>

            <div className="bg-slate-950 border border-slate-800 p-4 rounded-lg">
              <h3 className="mb-2 font-bold text-slate-100">
                The Convolution Operation
              </h3>
              <p className="mb-3 text-xs text-slate-400">
                Instead of connecting every pixel to every neuron, CNNs slide a
                small matrix (a "Kernel" or "Filter") across the image.
              </p>
              <ul className="list-disc space-y-2 pl-5 text-cyan-200 text-xs">
                <li>
                  <strong>Kernels:</strong> Small grids (e.g., 3x3) of weights.
                  In early layers, they act like magnifying glasses hunting for
                  edges or corners.
                </li>
                <li>
                  <strong>Feature Maps:</strong> The output grid generated by
                  the sliding window. It lights up where the filter finds a
                  match.
                </li>
              </ul>
            </div>

            <div className="bg-slate-950 border border-slate-800 p-4 rounded-lg">
              <h3 className="mb-2 font-bold text-slate-100">Max Pooling</h3>
              <p className="text-xs text-slate-400">
                After a convolution, we usually apply a "Max Pooling" layer.
                This shrinks the feature map by only keeping the highest value
                in a given window, drastically reducing computational cost while
                keeping the most important detected features.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="flex-1 flex flex-col relative bg-slate-950 animate-fade-in">
        <div className="flex-1 w-full h-full relative overflow-hidden">
          <CNNVisualizer />
        </div>

        <div className="h-24 border-t border-slate-800 bg-slate-900 flex items-center justify-between px-8 z-10">
          <p className="text-xs text-slate-400 font-mono">
            Kernel Mapping & Matrix Math
          </p>
          <Link
            href="/ai/computer-vision/quiz"
            className="px-8 py-3 bg-purple-600 hover:bg-purple-500 text-white rounded-lg font-bold transition shadow-md"
          >
            Take Assessment (+300 AI XP)
          </Link>
        </div>
      </div>
    </section>
  );
}
