"use client";

import Link from "next/link";
import CNNVisualizer from "@/components/canvas/CNNVisualizer";

export default function ComputerVisionPage() {
  return (
    <div className="flex h-full w-full flex-col overflow-hidden text-slate-200">
      <main className="flex-1 overflow-y-auto p-8">
        <div className="mx-auto grid max-w-7xl grid-cols-1 gap-8 xl:grid-cols-2">
          <section className="flex flex-col rounded-xl border border-purple-900/30 bg-slate-900/50 p-8 shadow-2xl backdrop-blur-sm">
            <div className="mb-2 text-sm font-bold tracking-widest text-purple-500 uppercase">
              AI Track • Level 7
            </div>
            <h1 className="mb-6 text-4xl font-extrabold text-slate-100">
              Computer Vision (CNNs)
            </h1>

            <div className="space-y-4 text-slate-300 leading-relaxed text-sm">
              <p>
                Standard neural networks flatten images into long lists of
                numbers, destroying the spatial relationships between pixels. To
                solve this, we use{" "}
                <strong className="text-purple-400">
                  Convolutional Neural Networks (CNNs)
                </strong>
                .
              </p>

              <div className="rounded-lg border border-slate-800 bg-slate-950 p-4">
                <h3 className="mb-2 font-bold text-slate-100">
                  The Convolution Operation
                </h3>
                <p className="mb-3 text-xs text-slate-400">
                  Instead of connecting every pixel to every neuron, CNNs slide
                  a small matrix (a "Kernel" or "Filter") across the image.
                </p>
                <ul className="list-disc space-y-2 pl-5 text-cyan-200 text-xs">
                  <li>
                    <strong>Kernels:</strong> Small grids (e.g., 3x3) of
                    weights. In early layers, they act like magnifying glasses
                    hunting for edges or corners.
                  </li>
                  <li>
                    <strong>Feature Maps:</strong> The output grid generated by
                    the sliding window. It lights up where the filter finds a
                    match.
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-slate-800 bg-slate-950 p-4">
                <h3 className="mb-2 font-bold text-slate-100">Max Pooling</h3>
                <p className="text-xs text-slate-400">
                  After a convolution, we usually apply a "Max Pooling" layer.
                  This shrinks the feature map by only keeping the highest value
                  in a given window, drastically reducing computational cost
                  while keeping the most important detected features.
                </p>
              </div>
            </div>

            <div className="mt-8">
              <Link
                href="/ai/computer-vision/quiz"
                className="inline-flex w-fit items-center rounded-lg bg-purple-600 px-6 py-3 font-semibold text-white shadow-[0_0_20px_rgba(147,51,234,0.3)] hover:bg-purple-500"
              >
                Take Assessment (+300 AI XP)
              </Link>
            </div>
          </section>

          <section className="relative flex min-h-[550px] items-center justify-center overflow-hidden rounded-xl border border-slate-800 bg-black shadow-2xl xl:col-span-1">
            <CNNVisualizer />
          </section>
        </div>
      </main>
    </div>
  );
}
